spring.application.name=veiculo
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/camara_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jackson.time-zone=America/Sao_Paulo

app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password=${ADMIN_PASSWORD:admin123}

app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:4200}

server.forward-headers-strategy=framework